'use strict';

// ============================================================
// LANG — 多言語対応。新言語追加は LANGS にエントリを追加するだけ。
// LANG_ORDER で表示順を制御。
// ============================================================
const LANGS = {
  ja: {
    name:        '日本語',
    score:       'スコア',
    best:        '最高',
    next:        '次の天体',
    gameOver:    'ゲームオーバー',
    stageClear:  'ステージクリア！',
    timeUp:      'タイムアップ！',
    goalLabel:   '目標',
    modeStage:        'ステージ',
    modeEndless:      'エンドレス',
    modeSelectTitle:  'モードを選択',
    modeDescTime:     '3分間でハイスコアを目指す',
    modeDescEndless:  '時間制限なしで遊ぶ',
    scoreResult: 'スコア',
    newRecord:   '🏆 新記録！',
    retry:       'もう一度',
    backToHome:  'ホームに戻る',
    nextStage:   '次へ進む',
    menuTitle:   'メニュー',
    settingsBack: '← 戻る',
    settings:    '設定',
    resume:      'ゲームに戻る',
    reset:       'リセット',
    title:       'ころころ宇宙',
    start:       'スタート',
    skipTutorial: 'チュートリアルをスキップ',
    skillBomb:    '爆弾',
    skillUpgrade: '強化',
    skillDelete:  '削除',
    chain: n => `${n}連鎖！`,
    rouletteTitle: '4連鎖！ スキル獲得',
    rouletteStop: '停止',
    bombDesc:    '範囲内の天体を消去',
    upgradeDesc: '天体を1段階強化',
    deleteDesc:  '天体を削除',
    chooseSkill:   'スキルを選択',
    confirmDelete: 'を削除',
    queueWaiting:  n => `あと ${n} 件待機中`,
    queueMore:     n => `あと ${n} 件`,
    reward:        '報酬',
    autoshow:      on => `報酬自動表示: ${on ? 'ON' : 'OFF'}`,
    sfxVolume:     '効果音',
    shareBtn:      'X でシェア',
    sharePreparing: '準備中...',
    rankingBtn:    '🏆 ランキング',
    gamesLink:     '🎮 ゲーム一覧',
    displayNameLabel: '表示名',
    displayNamePlaceholder: '15文字以内（日本語OK）',
    displayNameSave: '保存',
    displayNameSaved: '✓ 保存しました',
    displayNameEmpty: '1文字以上入力してください',
    profileLink: '👤 プロフィール',
    startNameHint:   'ここで名前を変えられます ✎',
    startNameHintOk: 'わかった',
    achievements:   '🏆 実績',
    achNewUnlock:   '実績解除！',
    achBack:        '← 戻る',
    tutHint:        'タップして強化！',
    tweetText:     n => `ころころ宇宙で ${n} 点獲得！ #ころころ宇宙`,
    shareNote:     '📥 盤面画像をダウンロードしました。ツイートに添付してください。',
    rankPct:       pct => `全体の上位 ${pct}% ✨`,
    skillHintBomb:    '💣 次の投下に爆弾を使います。着地後に爆発！',
    skillHintUpgrade: '⬆ 天体を1つタップして1段階強化します',
    skillHintDelete:  '✕ 天体を1つタップして削除します',
    forcedTitleBomb:    '爆弾モード',
    forcedDescBomb:     '爆弾を落とせ！',
    forcedTitleUpgrade: '進化モード',
    forcedDescUpgrade:  '天体を進化させよ',
    forcedTitleDelete:  '消去モード',
    forcedDescDelete:   '削除する天体を選択せよ',
    credits:            'クレジット',
    creditsTitle:       'クレジット',
    creditsSfxHead:     '効果音素材',
    creditsSfxNote:     '各サービスの利用規約に基づき効果音素材を使用しています。',
    creditsImgHead:     '画像・ビジュアル素材',
    creditsImgNote:     '一部画像・ビジュアル素材の制作には ChatGPT を使用しています。',
    cosmosBtn:          '🌌 宇宙',
    cosmosTitle:        '宇宙',
    stardust:           '星屑',
    stellarEnergy:      '恒星エネルギー',
    energyRate:         '/秒',
    generatorTitle:     '物質生成器',
    generatorLevel:     n => `Lv ${n}`,
    generatorUpgrade:   '強化',
    generatorMax:       'MAX',
    planetCount:        (n, s) => `🪐 惑星 ${n} / ${s}`,
    planetAdd:          '＋ 惑星を追加',
    planetLockedAt:     lv => `🔒 Lv${lv} でスロット解放`,
    planetNextSlot:     lv => `次のスロットは Lv${lv}`,
    planetSlotsFull:    'スロット上限',
    planetModalTitle:   '惑星を追加',
    planetModalAdd:     '生成',
    planetModalCancel:  'キャンセル',
    planetNamePlaceholder: '惑星の名前（15文字以内）',
    growthPct:           p => `🔥 成長 ${p}%`,
    supernovaReady:      '💥 超新星',
    supernovaLocked:     d => `100% まで ${d}%`,
    supernovaWarn:       th => `⚠️ 不安定です (${th}%)`,
    supernovaCapped:     '⛔ 進行不能。超新星を実行してください',
    supernovaModalTitle: '超新星を実行',
    supernovaModalDesc:  (g, p) => `成長 ${g}% の恒星と ${p} 個の惑星を爆発させ、文明ポイントを得ます。恒星と惑星はリセットされます。`,
    supernovaModalOk:    '実行',
    supernovaModalCancel:'キャンセル',
    rewardGained:       '獲得',
    massInfo:           (m, r) => `🪨 質量 ${m}  +${r}/秒`,
    offlineGain:        n => `放置中に +${n} 恒星エネルギー`,
    offlineTitle:       '放置報酬',
    offlineDuration:    (h, m) => h > 0 ? `${h}時間 ${m}分 の放置` : `${m}分 の放置`,
    offlineEnergyLabel: '⚡ 恒星エネルギー',
    offlineCollectBtn:  '受け取る',
    feedbackBtn:        '💬 フィードバック',
    feedbackTitle:      'フィードバックを送る',
    feedbackPlaceholder:'感想・バグ報告・要望など、なんでも自由にどうぞ（1〜1000文字）',
    feedbackSend:       '送信',
    feedbackCancel:     'キャンセル',
    feedbackSending:    '送信中…',
    feedbackThanks:     'ありがとうございます！',
    feedbackError:      '送信に失敗しました。少し時間をおいて再試行してください',
    feedbackRateLimit:  '送信回数の上限に達しました。少し時間をおいてください',
    cosmosClose:        '閉じる',
    navCosmos:          '恒星',
    navResearch:        '研究',
    navPlay:            'プレイ',
    navAch:             '実績',
    navRanking:         'ランキング',
    modeSelectTitle:    'モード選択',
    researchTitle:      '研究',
    researchTabNormal:  '通常',
    researchTabPerm:    '永続',
    civLevelLabel:      n => `文明レベル ${n}`,
    civNextCost:        n => `次のレベル: ⚡ ${n}`,
    civMax:             '文明レベル MAX',
    civUpBtn:           'レベルアップ',
    researchOwned:      '所持済み',
    researchReqCiv:     n => `🔒 Lv${n} で解禁`,
    tabEndless:         'エンドレス',
    tabTime:            'タイムアタック',
    tabDaily:           '今日',
    tabWeekly:          '今週',
    tabAll:             '全期間',
    rankingFull:        'フルランキング →',
    rankLoading:        '読み込み中...',
    rankError:          '読み込みに失敗しました',
    rankEmpty:          'まだ記録がありません',
    tutDropHint:        'タップして天体を落とそう',
  },
  en: {
    name:        'English',
    score:       'Score',
    best:        'Best',
    next:        'Next',
    gameOver:    'Game Over',
    stageClear:  'STAGE CLEAR!',
    timeUp:      "TIME'S UP!",
    goalLabel:   'Goal',
    modeStage:        'Stage',
    modeEndless:      'Endless',
    modeSelectTitle:  'Select Mode',
    modeDescTime:     'Go for the high score in 3 minutes',
    modeDescEndless:  'Play without a time limit',
    scoreResult: 'Score',
    newRecord:   '🏆 New Record!',
    retry:       'Play Again',
    backToHome:  'Back to Home',
    nextStage:   'Next Stage',
    menuTitle:   'Menu',
    settingsBack: '← Back',
    settings:    'Settings',
    resume:      'Resume',
    reset:       'Reset',
    title:       'Rollaxy',
    start:       'Start',
    skipTutorial: 'Skip Tutorial',
    skillBomb:    'Bomb',
    skillUpgrade: 'Upgrade',
    skillDelete:  'Delete',
    chain: n => `${n} Chain!`,
    rouletteTitle: '4 Chain! Skill Reward',
    rouletteStop: 'STOP',
    bombDesc:    'Destroy nearby bodies',
    upgradeDesc: 'Upgrade a body by 1',
    deleteDesc:  'Remove a body',
    chooseSkill:   'Choose Skill',
    confirmDelete: ' Delete',
    queueWaiting:  n => `+${n} queued`,
    queueMore:     n => `+${n} more`,
    reward:        'Reward',
    autoshow:      on => `Auto Reward: ${on ? 'ON' : 'OFF'}`,
    sfxVolume:     'SFX',
    shareBtn:      'Share on X',
    sharePreparing: 'Preparing...',
    rankingBtn:    '🏆 Ranking',
    gamesLink:     '🎮 Games',
    displayNameLabel: 'Display Name',
    displayNamePlaceholder: 'Up to 15 chars',
    displayNameSave: 'Save',
    displayNameSaved: '✓ Saved',
    displayNameEmpty: 'Please enter at least 1 character',
    profileLink: '👤 Profile',
    startNameHint:   'You can change your name here ✎',
    startNameHintOk: 'Got it',
    achievements:   '🏆 Achievements',
    achNewUnlock:   'Achievement Unlocked!',
    achBack:        '← Back',
    tutHint:        'Tap to Upgrade!',
    tweetText:     n => `I scored ${n} in Rollaxy! #Rollaxy`,
    shareNote:     '📥 Image downloaded. Please attach it to your tweet.',
    rankPct:       pct => `Top ${pct}% overall ✨`,
    skillHintBomb:    '💣 Bomb drops as your next body. Explodes on landing!',
    skillHintUpgrade: '⬆ Tap a body to upgrade it by 1 tier',
    skillHintDelete:  '✕ Tap a body to remove it',
    forcedTitleBomb:    'Bomb Mode',
    forcedDescBomb:     'Drop the bomb!',
    forcedTitleUpgrade: 'Evolve Mode',
    forcedDescUpgrade:  'Evolve a body!',
    forcedTitleDelete:  'Erase Mode',
    forcedDescDelete:   'Select a body to erase',
    credits:            'Credits',
    creditsTitle:       'Credits',
    creditsSfxHead:     'Sound Effects',
    creditsSfxNote:     'Used under the respective terms of service.',
    creditsImgHead:     'Images & Visuals',
    creditsImgNote:     'Some visuals were created using ChatGPT.',
    cosmosBtn:          '🌌 Cosmos',
    cosmosTitle:        'Cosmos',
    stardust:           'Stardust',
    stellarEnergy:      'Stellar Energy',
    energyRate:         '/s',
    generatorTitle:     'Matter Generator',
    generatorLevel:     n => `Lv ${n}`,
    generatorUpgrade:   'Upgrade',
    planetCount:        (n, s) => `🪐 Planets ${n} / ${s}`,
    planetAdd:          '＋ Add Planet',
    planetLockedAt:     lv => `🔒 Unlocks at Lv${lv}`,
    planetNextSlot:     lv => `Next slot at Lv${lv}`,
    planetSlotsFull:    'Slots full',
    planetModalTitle:   'Add a Planet',
    planetModalAdd:     'Create',
    planetModalCancel:  'Cancel',
    planetNamePlaceholder: 'Planet name (max 15)',
    growthPct:           p => `🔥 Growth ${p}%`,
    supernovaReady:      '💥 Supernova',
    supernovaLocked:     d => `${d}% to 100%`,
    supernovaWarn:       th => `⚠️ Unstable (${th}%)`,
    supernovaCapped:     '⛔ Capped. Trigger supernova',
    supernovaModalTitle: 'Trigger Supernova',
    supernovaModalDesc:  (g, p) => `Detonate the ${g}% star with ${p} planet(s) to earn Civilization Points. Star and planets will reset.`,
    supernovaModalOk:    'Detonate',
    supernovaModalCancel:'Cancel',
    generatorMax:       'MAX',
    rewardGained:       'Earned',
    massInfo:           (m, r) => `🪨 Mass ${m}  +${r}/s`,
    offlineGain:        n => `+${n} stellar energy while away`,
    offlineTitle:       'Offline Reward',
    offlineDuration:    (h, m) => h > 0 ? `Away for ${h}h ${m}m` : `Away for ${m}m`,
    offlineEnergyLabel: '⚡ Stellar Energy',
    offlineCollectBtn:  'Collect',
    feedbackBtn:        '💬 Feedback',
    feedbackTitle:      'Send Feedback',
    feedbackPlaceholder:'Thoughts, bug reports, requests — anything goes (1–1000 chars)',
    feedbackSend:       'Send',
    feedbackCancel:     'Cancel',
    feedbackSending:    'Sending…',
    feedbackThanks:     'Thanks for the feedback!',
    feedbackError:      'Failed to send. Please try again later.',
    feedbackRateLimit:  'Too many submissions. Please wait a bit.',
    cosmosClose:        'Close',
    navCosmos:          'Star',
    navResearch:        'Research',
    navPlay:            'Play',
    navAch:             'Awards',
    navRanking:         'Ranking',
    modeSelectTitle:    'Select Mode',
    researchTitle:      'Research',
    researchTabNormal:  'Normal',
    researchTabPerm:    'Permanent',
    civLevelLabel:      n => `Civilization Lv ${n}`,
    civNextCost:        n => `Next level: ⚡ ${n}`,
    civMax:             'Civilization MAX',
    civUpBtn:           'Level Up',
    researchOwned:      'Owned',
    researchReqCiv:     n => `🔒 Unlocks at Lv${n}`,
    tabEndless:         'Endless',
    tabTime:            'Time Attack',
    tabDaily:           'Today',
    tabWeekly:          'This Week',
    tabAll:             'All Time',
    rankingFull:        'Full ranking →',
    rankLoading:        'Loading...',
    rankError:          'Failed to load',
    rankEmpty:          'No records yet',
    tutDropHint:        'Tap to drop a body',
  },
  zh: {
    name:        '中文',
    score:       '分数',
    best:        '最高',
    next:        '下一个',
    gameOver:    '游戏结束',
    stageClear:  '通关！',
    timeUp:      '时间到！',
    goalLabel:   '目标',
    modeStage:        '关卡',
    modeEndless:      '无尽',
    modeSelectTitle:  '选择模式',
    modeDescTime:     '在3分钟内争取高分',
    modeDescEndless:  '无时间限制地游戏',
    scoreResult: '分数',
    newRecord:   '🏆 新纪录！',
    retry:       '再来一次',
    backToHome:  '返回主页',
    nextStage:   '下一关',
    menuTitle:   '菜单',
    settingsBack: '← 返回',
    settings:    '设置',
    resume:      '返回游戏',
    reset:       '重置',
    title:       'Rollaxy',
    start:       '开始',
    skipTutorial: '跳过教程',
    skillBomb:    '炸弹',
    skillUpgrade: '强化',
    skillDelete:  '删除',
    chain: n => `${n}连锁！`,
    rouletteTitle: '4连锁！ 获得技能',
    rouletteStop: '停止',
    bombDesc:    '消除范围内的天体',
    upgradeDesc: '天体升级1阶',
    deleteDesc:  '删除天体',
    chooseSkill:   '选择技能',
    confirmDelete: ' 删除',
    queueWaiting:  n => `还有 ${n} 个等待`,
    queueMore:     n => `还有 ${n} 个`,
    reward:        '奖励',
    autoshow:      on => `自动显示奖励: ${on ? '开' : '关'}`,
    sfxVolume:     '音效',
    shareBtn:      '分享到 X',
    sharePreparing: '准备中...',
    rankingBtn:    '🏆 排行榜',
    gamesLink:     '🎮 游戏列表',
    displayNameLabel: '显示名称',
    displayNamePlaceholder: '最多15个字符',
    displayNameSave: '保存',
    displayNameSaved: '✓ 已保存',
    displayNameEmpty: '请至少输入1个字符',
    profileLink: '👤 个人资料',
    startNameHint:   '点击 ✎ 可以修改名字',
    startNameHintOk: '知道了',
    achievements:   '🏆 实绩',
    achNewUnlock:   '成就解锁！',
    achBack:        '← 返回',
    tutHint:        '点击强化！',
    tweetText:     n => `我在 Rollaxy 获得了 ${n} 分！ #Rollaxy`,
    shareNote:     '📥 已下载盘面图片，请将其附加到推文中。',
    rankPct:       pct => `全服前 ${pct}% ✨`,
    skillHintBomb:    '💣 将炸弹作为下一个投放物使用，落地后爆炸！',
    skillHintUpgrade: '⬆ 点击一个天体将其升级一阶',
    skillHintDelete:  '✕ 点击一个天体将其删除',
    forcedTitleBomb:    '炸弹模式',
    forcedDescBomb:     '投下炸弹！',
    forcedTitleUpgrade: '进化模式',
    forcedDescUpgrade:  '让天体进化！',
    forcedTitleDelete:  '消除模式',
    forcedDescDelete:   '选择要删除的天体',
    credits:            '制作人员',
    creditsTitle:       '制作人员',
    creditsSfxHead:     '音效素材',
    creditsSfxNote:     '依据各服务条款使用。',
    creditsImgHead:     '图像·视觉素材',
    creditsImgNote:     '部分素材使用了 ChatGPT 制作。',
    cosmosBtn:          '🌌 宇宙',
    cosmosTitle:        '宇宙',
    stardust:           '星屑',
    stellarEnergy:      '恒星能量',
    energyRate:         '/秒',
    generatorTitle:     '物质生成器',
    generatorLevel:     n => `Lv ${n}`,
    generatorUpgrade:   '强化',
    planetCount:        (n, s) => `🪐 行星 ${n} / ${s}`,
    planetAdd:          '＋ 添加行星',
    planetLockedAt:     lv => `🔒 Lv${lv} 解锁槽位`,
    planetNextSlot:     lv => `下一槽位 Lv${lv}`,
    planetSlotsFull:    '槽位已满',
    planetModalTitle:   '添加行星',
    planetModalAdd:     '生成',
    planetModalCancel:  '取消',
    planetNamePlaceholder: '行星名称（最多15字）',
    growthPct:           p => `🔥 成长 ${p}%`,
    supernovaReady:      '💥 超新星',
    supernovaLocked:     d => `距 100% 还差 ${d}%`,
    supernovaWarn:       th => `⚠️ 不稳定 (${th}%)`,
    supernovaCapped:     '⛔ 已到上限，请引爆超新星',
    supernovaModalTitle: '引爆超新星',
    supernovaModalDesc:  (g, p) => `引爆成长 ${g}% 的恒星和 ${p} 颗行星，获得文明点数。恒星与行星将被重置。`,
    supernovaModalOk:    '引爆',
    supernovaModalCancel:'取消',
    generatorMax:       'MAX',
    rewardGained:       '获得',
    massInfo:           (m, r) => `🪨 质量 ${m}  +${r}/秒`,
    offlineGain:        n => `挂机期间 +${n} 恒星能量`,
    offlineTitle:       '离线奖励',
    offlineDuration:    (h, m) => h > 0 ? `离开了 ${h}小时 ${m}分钟` : `离开了 ${m}分钟`,
    offlineEnergyLabel: '⚡ 恒星能量',
    offlineCollectBtn:  '领取',
    feedbackBtn:        '💬 反馈',
    feedbackTitle:      '发送反馈',
    feedbackPlaceholder:'感想、bug 报告、需求等，欢迎自由填写（1〜1000 字）',
    feedbackSend:       '发送',
    feedbackCancel:     '取消',
    feedbackSending:    '发送中…',
    feedbackThanks:     '感谢您的反馈！',
    feedbackError:      '发送失败。请稍后重试',
    feedbackRateLimit:  '已达到发送次数上限。请稍候',
    cosmosClose:        '关闭',
    navCosmos:          '恒星',
    navResearch:        '研究',
    navPlay:            '开始',
    navAch:             '成就',
    navRanking:         '排行榜',
    modeSelectTitle:    '选择模式',
    researchTitle:      '研究',
    researchTabNormal:  '常规',
    researchTabPerm:    '永久',
    civLevelLabel:      n => `文明等级 ${n}`,
    civNextCost:        n => `下一级: ⚡ ${n}`,
    civMax:             '文明等级 MAX',
    civUpBtn:           '升级',
    researchOwned:      '已拥有',
    researchReqCiv:     n => `🔒 Lv${n} 解锁`,
    tabEndless:         '无尽模式',
    tabTime:            '限时挑战',
    tabDaily:           '今日',
    tabWeekly:          '本周',
    tabAll:             '全部',
    rankingFull:        '完整排行榜 →',
    rankLoading:        '加载中...',
    rankError:          '加载失败',
    rankEmpty:          '暂无记录',
    tutDropHint:        '点击放下天体',
  },
};

// 言語ボタンの表示順
const LANG_ORDER = ['ja', 'en', 'zh'];

// 現在の言語（localStorage で永続化）— novora_lang キーに統一（旧 rollaxy_lang からも移行）
// 明示的な保存がない初回アクセス時は navigator.language から自動検出する。
// 自動検出結果は localStorage に書かない（設定画面での明示操作と区別するため）。
function _detectLang() {
  const stored = localStorage.getItem(STORAGE_KEYS.LANG) || localStorage.getItem(STORAGE_KEYS.LEGACY_LANG);
  if (stored && LANGS[stored]) return stored;
  const nav = (navigator.language || navigator.userLanguage || '').toLowerCase();
  for (const code of LANG_ORDER) {
    if (nav === code || nav.startsWith(code + '-')) return code;
  }
  return 'en'; // 対応言語なし → 英語にフォールバック
}
let currentLang = _detectLang();
document.documentElement.lang = currentLang;

// キーから現在言語の文字列を取得
function T(key) {
  return (LANGS[currentLang] || LANGS.ja)[key];
}

// 言語を切り替えて画面に反映
function setLang(code) {
  if (!LANGS[code]) return;
  currentLang = code;
  localStorage.setItem(STORAGE_KEYS.LANG, code);
  localStorage.removeItem(STORAGE_KEYS.LEGACY_LANG); // 旧キーを削除
  document.documentElement.lang = code;
  applyLang();
}

// data-i18n 属性を持つ全要素のテキストを更新し、langchange イベントを発火
function applyLang() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const val = T(el.dataset.i18n);
    if (typeof val === 'string') el.textContent = val;
  });
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === currentLang);
  });
  // game.js 側でスコア表示など動的文字列を再描画させる
  document.dispatchEvent(new Event('langchange'));
}
